apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lab6-prod

resources:
  - ../../base
  - namespace.yaml
  - secret.yaml

patches:
  - path: patch-backend.yaml
  - path: patch-frontend.yaml
  - path: patch-configmap.yaml

labels:
  - includeSelectors: true
    pairs:
      environment: prod