apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab6-backend
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "600m"
              memory: "512Mi"