apiVersion: v1
kind: Secret
metadata:
  name: lab6-app-secret
type: Opaque
stringData:
  demo-api-key: "REPLACE_WITH_SECRET_FROM_CI"
  database-url: "postgres://lab6_user:REPLACE_WITH_SECRET_FROM_CI@postgres-0.postgres.lab6-data.svc.cluster.local:5432/lab6_app?sslmode=disable"