apiVersion: v1
kind: ConfigMap
metadata:
  name: lab6-app-config
data:
  APP_ENV: "base"
  APP_VERSION: "2.0.0"
  config.js: |
    window.APP_CONFIG = {
      APP_TITLE: "Лабораторная работа 6: Kustomize, Helm и PostgreSQL",
      API_BASE_URL: ""
    };