apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab6-frontend
  labels:
    app: lab6-web-app
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab6-web-app
      component: frontend
  template:
    metadata:
      labels:
        app: lab6-web-app
        component: frontend
    spec:
      containers:
        - name: frontend
          image: lab6-frontend:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: frontend-config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "192Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
      volumes:
        - name: frontend-config
          configMap:
            name: lab6-app-config
            items:
              - key: config.js
                path: config.js