apiVersion: v1
kind: Secret
metadata:
  name: lab6-app-secret
type: Opaque
stringData:
  demo-api-key: "lab6-dev-demo-key"
  database-url: "postgres://lab6_user:lab6-dev-password@postgres-0.postgres:5432/lab6_app?sslmode=disable"