apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab6-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: lab6-web-app
    component: backend
    {{- include "lab6-web-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: lab6-web-app
      component: backend
  template:
    metadata:
      labels:
        app: lab6-web-app
        component: backend
        {{- include "lab6-web-app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: lab6-app-config
                  key: APP_ENV
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: lab6-app-config
                  key: APP_VERSION
            - name: DEMO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lab6-app-secret
                  key: demo-api-key
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lab6-app-secret
                  key: database-url
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5