apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-infra.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres-infra.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: postgres
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres